version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: playground
      MYSQL_USER: test
      MYSQL_PASSWORD: '123456'
